### ISSUE TITLE
manifest trying to clone something that is not reachable from net

### ISSUE THREAD

**Issue by skshandilya** [flatcar-linux/manifest#20]
flatcar-stable-2605.6.0
fatal: Cannot get https://gerrit.googlesource.com/git-repo/clone.bundle

not able to use this manifest to build custom images

**Environment and steps to reproduce**
cork create --manifest-branch flatcar-stable-2605.6.0
2020-10-07T05:17:14Z cork: Detecting SDK version
2020-10-07T05:17:16Z cork: Found SDK version 2605.0.0 from remote repo
2020-10-07T05:17:16Z cork: Downloading SDK version 2605.0.0
2020-10-07T05:18:23Z sdk: Unpacking SDK into /home/sanshand/chroot
sudo password for sanshand: 
2020-10-07T05:22:02Z sdk: Unpacked
gpg: keybox '/home/sanshand/.repoconfig/gnupg/pubring.kbx' created
gpg: /home/sanshand/.repoconfig/gnupg/trustdb.gpg: trustdb created
gpg: key 16530D5E920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: key 67B7E448692B382C: public key "Conley Owens <cco3@android.com>" imported
gpg: Total number processed: 2
gpg:               imported: 2

fatal: Cannot get https://gerrit.googlesource.com/git-repo/clone.bundle
fatal: error [Errno -2] Name or service not known
fatal: cloning the git-repo repository failed, will remove '.repo/repo' 
2020-10-07T05:22:25Z cork: repo init failed: exit status 1
platform ubuntu 20.04.1

**Comment by pothos** [comment]
Hi,
since you reported on https://github.com/flatcar-linux/Flatcar/issues/206 I will close it here. Please respond there if you hit this again. I just checked and the URL seems available.
